### ISSUE TITLE
Migrate content

### ISSUE THREAD

**Issue by sggerard** [bcgov/mem-mmti-public#404]
Migrate content from hard coded html files into the chosen CMS solution so users can easily edit and update it.

Copy and enter data from static html files into Strapi using the page template. Modify the page template as necessary.
Once complete make a backup of the postgres database and add it to this ticket to be shared between other team members.

Pages:
- Authorizations, compliance-oversight, contact, legislation, reclamation, tailings-management, topics-of-interest, water-quality, home

Considerations:
- Home & Contact pages might use a different template
- Ensure all links, paragraphs, headings and lists have the correct html syntax. i.e `<ul><li></li></ul>` Can be done by clicking the edit source button.

**Comment by sggerard** [comment]
For this task use the dev database, not your local version.

To connect to the dev database:
1. Login to openshift and copy the login token (Click your name in the top right)
2. In a terminal paste and run the login command.
3. Ensure no other postgres instance is running or choose another port (`brew services stop postgresql`)
4. Run the command: `oc port-forward cms-postgres-1-2cn2c 5432:5432 -n f00029-dev ` (If the pod restarts the pod name may change)
5. Login to strapi: Sustainment.Team@gov.bc.ca, password is in discord
6. Start strapi with `npm run develop`

**Comment by sggerard** [comment]
Pages created in the CMS will be accessible by using the entered route. However existing routes will not be overwritten. For testing purposes temporarily create a different route i.e authorizations2. Later on we will delete the existing routes for the static pages which are located in `app.routes.ts`

**Comment by raarielgrace** [comment]
A bug was found in Strapi that will slow down content migration. When inputting a link with innerText, such as `<a href="blah">hello</a>`, Strapi will turn the child node into a link as well, i.e. `<a href="blah"><a href="">hello</a></a>`.

I looked into the Strapi packages and found that the javascript that performs the editing logic (in the `ckeditor-engine` package and `eckeditor-editor-*` packages) does not seem to load in the frontend. I say this because breakpoints were not activating and console.log statements were not printing to the console. Edits also didn't trigger network calls, so the logic couldn't be performed on a server. Frankly, I have no clue how it works.

Similar bugs have been reported to the GitHub repo. Fixing this ourselves would eat up a lot of time. The simpler solution is to manually re-add each link during content migration.

**Comment by raarielgrace** [comment]
I found a way around the bug! The inner <a> element is made by the editor when it attempts to edit the attributes. For example:

`<a href="blah" target="_blank" rel="noopener">link</a>`
will be turned into
`<a href="blah" target="_blank" rel="noopener noreferrer"><a target="_blank" rel="noopener">link</a></a>`
when the editor automatically adds the `noreferrer` relationship.

If the <a> element is added with everything that the editor expects, it won't make any changes. (i.e. `<a href="blah" target="_blank" rel="noopener noreferrer">link</a>` will remain a functional link)

**Comment by raarielgrace** [comment]
Another quirk:

Some of the links use angular properties. The editor cannot replicate these links. An href property can be added that mimics the behaviour.

`<a [routerLink]="['/authorizations']" fragment="minesActPermits">Mines Act permit</a>`
should be turned into
`<a href="/authorizations#minesActPermits">Mines Act permit</a>`
to yield the same route.
