### ISSUE TITLE
determine how strapi will work with keycloak

### ISSUE THREAD

**Issue by jakemorr** [bcgov/mem-mmti-public#416]
**Problem Description** 
**In order to** determine how keyclok should be integrated with BCMI, we need to know whether we can use the existing NRPTI keycloak realm or if we need to request a new one from the BC Gov SSO Team

**Solution Needs**
- we need to know what path we are taking (NRPTI keycloak vs new realm)
- we need to know the steps required to integrate Strapi with either keycloak realm to manage the content for BCMI

**Timebox**
2 days

**Outcome**
Details describing the outcome of the research 
- keycloak integration ticket is updagted with appropriate steps
- path towards integrating keyclock with strapi is clear
- we know which keycloak realm we need to use

**Additional Context**
-

**Comment by raarielgrace** [comment]
Strapi provides a plugin to configure SSO for the content website for free, but they paywall SSO for the admin portal. Luckily, it seems like someone has done the work before us and made a free keycloak plugin for the admin portal: [https://github.com/chordata-insight/strapi-plugin-sso](https://github.com/chordata-insight/strapi-plugin-sso)

Like our project, this plugin is made in Strapi v4 and very well might break when we upgrade, but that's a problem for later.

**Comment by raarielgrace** [comment]
Asked the SSO Rocketchat whether we could reuse the NRPTI keycloak or if we were required to make a new realm. I was told that, since we're using the standard realm for NRPTI instead of a custom realm (details on the difference [here](https://developer.gov.bc.ca/docs/default/component/css-docs/Useful-References/)) we need to make a new realm. So, to answer the solution needs:

- The BCMI keycloak will be created via a new SSO integration
- It will be added to the Strapi admin dashboard via the above plugin or, if issues arise with the plugin as-is, via a forked version of the plugin
